application: simonruppgreene-webapps
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images

- url: /js
  static_dir: js

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /(.*\.unity3d)
  static_files: unity/\1
  upload: unity/(.*\.unity3d)
  mime_type: application/vnd.unity

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: latest